# Run the package tests whenever a pull request is opened
# See https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven

name: Run Maven tests

on:
  pull_request:
    branches: [ "master" ]
  # Allows you to manually run the workflow (for testing)
  workflow_dispatch:

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    permissions:
      # allows this workflow to create check runs (their passing/failure is shown on the PR)
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/checkout@v4
        with:
          repository: aya-lang/aya
          path: aya
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: build and install aya
        working-directory: aya
        run: mvn install --batch-mode
      - name: Run test phase
        working-directory: main
        run: mvn verify --batch-mode